/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhitls_crypto_jce_provider_ProviderConfig */

#ifndef _Included_org_openhitls_crypto_jce_provider_ProviderConfig
#define _Included_org_openhitls_crypto_jce_provider_ProviderConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhitls_crypto_jce_provider_ProviderConfig
 * Method:    loadProviderNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_jce_provider_ProviderConfig_loadProviderNative
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     org_openhitls_crypto_jce_provider_ProviderConfig
 * Method:    unloadProviderNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_jce_provider_ProviderConfig_unloadProviderNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
