/*
 * Copyright (c) 2026 openHiTLS. All Rights Reserved.
 *
 * hitls4j is licensed under the Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *     http://license.coscl.org.cn/MulanPSL2
 *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhitls_crypto_jce_provider_ProviderConfig */

#ifndef _Included_org_openhitls_crypto_jce_provider_ProviderConfig
#define _Included_org_openhitls_crypto_jce_provider_ProviderConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhitls_crypto_jce_provider_ProviderConfig
 * Method:    loadProviderNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_jce_provider_ProviderConfig_loadProviderNative
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     org_openhitls_crypto_jce_provider_ProviderConfig
 * Method:    unloadProviderNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openhitls_crypto_jce_provider_ProviderConfig_unloadProviderNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
